"""cluster_id field was added for test_set

Revision ID: 483c01433a67
Revises: ca90c300f54
Create Date: 2013-09-25 18:55:06.167712

"""

# revision identifiers, used by Alembic.
revision = '483c01433a67'
down_revision = 'ca90c300f54'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sets', sa.Column('cluster_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_sets', 'cluster_id')
    ### end Alembic commands ###
