"""adds deployment_tags field fot test_sets and tests

Revision ID: ca90c300f54
Revises: 3e45add6471
Create Date: 2013-09-25 13:25:28.410172

"""

# revision identifiers, used by Alembic.
revision = 'ca90c300f54'
down_revision = '3e45add6471'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sets', sa.Column('deployment_tags', postgresql.ARRAY(sa.String(length=64)), nullable=True))
    op.add_column('tests', sa.Column('deployment_tags', postgresql.ARRAY(sa.String(length=64)), nullable=True))
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'deployment_tags')
    op.drop_column('test_sets', 'deployment_tags')
    ### end Alembic commands ###
